layout_spectrum: 0
typography_spectrum: 0.8617201
color:
  lightness: 0.4578415
  brandStrength: 0.8225389
  saturation: 0.372162
  rhythmicContrast: 0.7428331
  brandColors:
    - '#000000'
name: First visual ltd
