layout_spectrum: 0
name: First visual ltd
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8225389
  lightness: 0.4578415
  saturation: 0.372162
  rhythmicContrast: 0.7428331
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#6E6E6E'
    - '#C6C6C6'
    - '#393939'
typography_spectrum: 0.8617201
